### PR TITLE
Kore prove

### PR DESCRIPTION
**Pull request by traiansf**
https://trello.com/c/kLhYsSAT

### CODE REVIEW

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by traiansf** [comment]
Thanks! Yes, the proofs do not complete, but they seem to be starting appropriately.

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test mantis

**Comment by ehildenb** [comment]
Subsumed by #292.

**Pull request closed without merging**
