### PR TITLE
Verification cleanup

### PR DESCRIPTION
**Pull request by ehildenb**
Testing compatibility with https://github.com/kframework/evm-semantics/pull/133

### CODE REVIEW

**Comment by daejunpark** [comment]
@ehildenb @nishantjr @msaxena2 The failure seems to be due to the python version. `gen-spec.py` requires python 3.6. Could you double-check it?

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
subsumed

**Pull request closed without merging**
