### PR TITLE
Bool2 word fixes

### PR DESCRIPTION
**Pull request by ehildenb**
More fixes which should make the verification PR smaller/simpler

Do not merge yet, just want to test this batch of changes, more changes to come.

### CODE REVIEW

**Comment by ehildenb** [comment]
@daejunpark could you take a look at why the proofs fail with these changes? This switches the semantics to using the `_<Word_` infrastructure, which goes through `bool2Word`. The test output says Z3 is not receiving the definition of `smt_seq_elem`, which is declared in `domains.k` under the `LIST` module.

Fixing this issue should give us a clue about fixing the branch on top of this as well: https://github.com/kframework/evm-semantics/pull/139

`make build && make split-tests && make tests/proofs/hkg/transferFrom-else-spec.k.test` should reveal the test failure.

**Comment by daejunpark** [comment]
You missed `ISZERO`.

**Comment by daejunpark** [comment]
now `make tests/proofs/hkg/transferFrom-else-spec.k.test` passed.

**Comment by ehildenb** [comment]
@daejunpark looks like these changes significantly dropped the test running time too :) merging now

**Pull request merged**
