### PR TITLE
Update k submodule, add kast command to kevm.

### PR DESCRIPTION
**Pull request by ehildenb**

### CODE REVIEW

**Comment by ehildenb** [comment]
Must wait for https://github.com/kframework/k/pull/449

**Comment by dwightguth** [comment]
I'll wait until the tests pass to review this, but I spotted something suspicious: you removed the shift command from run_krun, but didn't change anything else in that function.

**Comment by ehildenb** [comment]
`run_file` is now set globally in the same way that `backend` and `run_command` are at the end of the script, so no need to set them in the procedures directly.

**Comment by ehildenb** [comment]
This PR has had the build system refactors pulled from it.

**Pull request merged**
