### PR TITLE
More tests now pass, some removed from `failing-symbolic.haskell`

### PR DESCRIPTION
**Pull request by Riib11**
Perhaps recent updates allow previously failing tests to now pass. To test this, locally ran the following 27 tests with the haskell backend:
```
tests/specs/functional/merkle-spec.k.prove
tests/specs/functional/lemmas-no-smt-spec.k.prove
tests/specs/functional/infinite-gas-spec.k.prove
tests/specs/benchmarks/functional-spec.k.prove
tests/specs/functional/lemmas-spec.k.prove
tests/specs/functional/storageRoot-spec.k.prove
tests/specs/evm-optimizations-spec.mk.prove
tests/specs/examples/sum-to-n-spec.k.prove
tests/specs/erc20/hkg/totalSupply-spec.k.prove
tests/specs/benchmarks/storagevar03-spec.k.prove
tests/specs/benchmarks/storagevar00-spec.k.prove
tests/specs/benchmarks/requires01-a0le0-spec.k.prove
tests/specs/benchmarks/storagevar01-spec.k.prove
tests/specs/benchmarks/storagevar02-overflow-spec.k.prove
tests/specs/benchmarks/address00-spec.k.prove
tests/specs/benchmarks/overflow00-overflow-spec.k.prove
tests/specs/benchmarks/overflow00-nooverflow-spec.k.prove
tests/specs/benchmarks/storagevar02-nooverflow-spec.k.prove
tests/specs/benchmarks/requires01-a0gt0-spec.k.prove
tests/specs/benchmarks/encodepacked-keccak01-spec.k.prove
tests/specs/benchmarks/staticarray00-spec.k.prove
tests/specs/benchmarks/staticloop00-a0lt10-spec.k.prove
tests/specs/erc20/ds/approve-failure-spec.k.prove
tests/specs/benchmarks/encode-keccak00-spec.k.prove
tests/specs/erc20/ds/totalSupply-spec.k.prove
tests/specs/benchmarks/keccak00-spec.k.prove
tests/specs/benchmarks/bytes00-spec.k.prove
```
Of these tests, the following 22 tests now pass:
```
tests/specs/functional/merkle-spec.k
tests/specs/functional/lemmas-no-smt-spec.k
tests/specs/functional/infinite-gas-spec.k
tests/specs/functional/storageRoot-spec.k
tests/specs/functional/lemmas-spec.k
tests/specs/benchmarks/functional-spec.k
tests/specs/erc20/hkg/totalSupply-spec.k
tests/specs/examples/sum-to-n-spec.k
tests/specs/benchmarks/storagevar03-spec.k
tests/specs/benchmarks/storagevar00-spec.k
tests/specs/benchmarks/requires01-a0le0-spec.k
tests/specs/benchmarks/storagevar01-spec.k
tests/specs/benchmarks/overflow00-overflow-spec.k
tests/specs/benchmarks/address00-spec.k
tests/specs/benchmarks/storagevar02-overflow-spec.k
tests/specs/benchmarks/overflow00-nooverflow-spec.k
tests/specs/benchmarks/storagevar02-nooverflow-spec.k
tests/specs/benchmarks/encodepacked-keccak01-spec.k
tests/specs/benchmarks/staticarray00-spec.k
tests/specs/benchmarks/staticloop00-a0lt10-spec.k
tests/specs/benchmarks/encode-keccak00-spec.k
tests/specs/benchmarks/bytes00-spec.k
```
Of these now-passing tests, the following 7 tests were in `failing-symbolic.haskell` and so were removed in order to enable testing them using CI:
```
tests/specs/benchmarks/requires01-a0le0-spec.k
tests/specs/benchmarks/address00-spec.k
tests/specs/benchmarks/overflow00-nooverflow-spec.k
tests/specs/benchmarks/encodepacked-keccak01-spec.k
tests/specs/benchmarks/staticarray00-spec.k
tests/specs/benchmarks/staticloop00-a0lt10-spec.k
tests/specs/benchmarks/bytes00-spec.k
```
Some of these tests may only pass in time longer than the CI timeout. Data on this will be provided soon.

### CODE REVIEW

**Comment by ehildenb** [comment]
The files `try-tests.sh` and `try-tests-old.out` should be removed from the repo. Otherwise looks good.

**Comment by ehildenb** [comment]
You can just add a commit removing them, no need to filter the history or anything.

**Comment by Riib11** [comment]
Timed results for the newly-enabled tests:
```
0 873.76s 730.70s 62.35s 2177608KB timeout 3000 kevm prove tests/specs/benchmarks/requires01-a0le0-spec.k VERIFICATION --backend haskell --format-failures --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
0 974.67s 781.45s 61.53s 1955556KB timeout 3000 kevm prove tests/specs/benchmarks/address00-spec.k VERIFICATION --backend haskell --format-failures --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
0 1028.00s 843.90s 87.85s 2027716KB timeout 3000 kevm prove tests/specs/benchmarks/overflow00-nooverflow-spec.k VERIFICATION --backend haskell --format-failures --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
0 1407.03s 1130.68s 143.85s 2387812KB timeout 3000 kevm prove tests/specs/benchmarks/encodepacked-keccak01-spec.k VERIFICATION --backend haskell --format-failures --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
0 1748.69s 1295.34s 108.71s 2131900KB timeout 3000 kevm prove tests/specs/benchmarks/staticarray00-spec.k VERIFICATION --backend haskell --format-failures --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
0 1570.08s 1329.28s 146.44s 2570004KB timeout 3000 kevm prove tests/specs/benchmarks/staticloop00-a0lt10-spec.k VERIFICATION --backend haskell --format-failures --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
1 828.96s 597.88s 76.97s 2274128KB timeout 3000 kevm prove tests/specs/benchmarks/bytes00-spec.k VERIFICATION --backend haskell --format-failures --concrete-rules-file tests/specs/benchmarks/concrete-rules.txt
```

**Comment by ehildenb** [comment]
Well it looks like `bytes00` is actually failing there, not just timing out. Timeout would have exit-code 124.

It looks like the longest running proof we have on CI right now is about 1200s. So let's enable just the first three in your list for now, and leave the remaining disabled for later performance improvements.

**Comment by Riib11** [comment]
> Well it looks like `bytes00` is actually failing there, not just timing out. Timeout would have exit-code 124.
> 
> It looks like the longest running proof we have on CI right now is about 1200s. So let's enable just the first three in your list for now, and leave the remaining disabled for later performance improvements.

Hmm, I must have mistaken that `bytes00` was actually passing. I'll go back and double check that. Alright next commit will leave just the first three of those tests enabled and the rest will be put back in `failing-symbolic.haskell`

**Review by ehildenb — APPROVED** [review]

**Pull request merged**
