### PR TITLE
Better test harness

### PR DESCRIPTION
**Pull request by ehildenb**
improvements to the `./Build` script and repository layout.

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by pirapira** [comment]
I'm waiting for this one before pushing #99.

**Comment by ehildenb** [comment]
@dwightguth can you review this when you get a chance? It contains the documentation changes and some updates to the testing harness. I have checked that the Jello Paper is generated correctly, if you could eyeball the changes to the testing harness that should be enough.

**Pull request merged**
