### PR TITLE
.build/{k,kore}: update submodules

### PR DESCRIPTION
**Pull request by traiansf**
I think this PR should make all tests in `tests/ethereum-tests/VMTests/vmArithmeticTest/divBoostBug.json` pass.  Did not test other dirs.

### CODE REVIEW

**Comment by ehildenb** [comment]
@dwightguth I remember you mentioning issues with the serialization stuffs, is this related? https://office.runtimeverification.com/jenkins/job/evm-semantics-pull-request/1176/console

Going to re-trigger tests anyway.

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by traiansf** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test mantis

**Pull request merged**
