### PR TITLE
bump k submodule

### PR DESCRIPTION
**Pull request by yzhang90**

### CODE REVIEW

**Comment by ehildenb** [comment]
@yzhang90 please use the same standard for commit messages that we've been using in the repo.

**Comment by yzhang90** [comment]
jekins: test this please.

**Comment by yzhang90** [comment]
jenkins: test this please.

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by shd101wyy** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test mantis

**Pull request merged**
