### PR TITLE
refactoring of EVM semantics in order to prepare for running KEVM in an Ethereum client

### PR DESCRIPTION
**Pull request by dwightguth**

### CODE REVIEW

**Comment by ehildenb** [comment]
@dwightguth not sure why the tests are not passing on Jenkins (and only some of them aren't). They pass on both Buildbot and on my own dev server. I will re-trigger a build, but am going to bed now.

Please review the changes I propose to the PR (marked with sss).

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
@dwightguth I added a commit (marked `!!!`) which you should review, also proposed a change for commit (marked `sss`) which should be squashed.

**Comment by dwightguth** [comment]
looks good.

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Pull request merged**
