### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by nishantjr**
This is to get the changes to Build, and what we currently have in verification through.

We've not been able to merge for a while, because of how long tests take to run, and before things get out of hand, I'd like this in.

### CODE REVIEW

**Comment by msaxena2** [comment]
Jenkins: test this please

**Comment by nishantjr** [comment]
add to whitelist

**Comment by msaxena2** [comment]
Jenkins: ok to test

**Comment by ehildenb** [comment]
Jenkins: please test this.

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by ehildenb** [comment]
Jenkins: test this please

**Pull request merged**
