### PR TITLE
Builtin bitrange

### PR DESCRIPTION
**Pull request by ehildenb**
Testing out https://github.com/kframework/k5/pull/99/

### CODE REVIEW

**Comment by ehildenb** [comment]
Jenkins: test this please

**Comment by daejunpark** [comment]
@ehildenb you may want to specify the semantics of `signextend` using the new hook.

**Comment by ehildenb** [comment]
@dwightguth I backed out the commit with uses the builtin `signExtendBitRangeInt` (tests were failing).

If you'd like me to try bringing it back to fix it, let me know.

**Comment by dwightguth** [comment]
Can you fix the commit history? You have duplicate commits here from Traian's PR.

**Pull request closed without merging**
