### PR TITLE
ABI-Proofs Rebased

### PR DESCRIPTION
**Pull request by msaxena2**
ABI complaint hkg token proofs.

### CODE REVIEW

**Comment by msaxena2** [comment]
Closing #107 - this PR has the related code. @daejunpark @ehildenb @bmmoore I'd like to get this in sometime today. The proofs are the same as the ones we used for the submissions. The proofs miss a few corner cases, and I'm making a note of them. Regardless, I'd like to get the abi-mechanism related code (which is independent of the proofs themselves) in before we proceed any further. The next step, of course would be to iron out the corner cases, and synchronize it with @grosu erc-20 repository.

**Comment by msaxena2** [comment]
Ugh. The proofs pass but the tests fail. Looking into it now.

**Comment by daejunpark** [comment]
I don't want to merge this as the current form. I'm not fully convinced with the verification lemmas. It seems to be too ad-hoc, which is ok for the experimental purpose but not for the master.

**Comment by msaxena2** [comment]
@daejunpark Yeah I agree, we can clean the lemmas up a bit. Probably an explanation of what each rule with the "smt-lemma" attribute does would also be helpful. Is your current work focused on just cleanup, or does it involve adding lemmas?

**Comment by daejunpark** [comment]
I'm trying a different approach, introducing an abstraction to avoid such low-level reasoning lemmas. Take a look at the viper branch.

**Comment by daejunpark** [comment]
close this since we have a replacement

**Pull request closed without merging**
