### PR TITLE
tests/proofs: update proofs submodule

### PR DESCRIPTION
**Pull request by daejunpark**
- add bihu proof
- add ds-token proof
- reorganize directory structure
- increase jvm memory to 5GB for kprove

### CODE REVIEW

**Comment by ehildenb** [comment]
The new proofs were not run by Buildbot, I'll investigate.

**Comment by ehildenb** [comment]
Looks like `make clean` was not removing makefile timestamp files. @daejunpark please review the last commit.

**Comment by daejunpark** [comment]
@ehildenb the last commit looks good to me. thanks!

**Comment by daejunpark** [comment]
Jenkins: test this please

**Pull request merged**
