### PR TITLE
Begin work executing blockchain tests

### PR DESCRIPTION
**Pull request by dwightguth**
**ready for review**

This code is intended to represent the initial draft of the code that executes the BlockchainTests test suite.

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
@ehildenb I'd like to work towards getting this merged, but it's dependent on some changes to UIUC-K. Is there someone who can work on getting codeship to pass, or do I need to take that task over as well?

**Comment by ehildenb** [comment]
@dwightguth what changes to UIUC-K do you need? Perhaps @lucaspena and I can work on it today.

**Comment by dwightguth** [comment]
I believe the only real change needed is to add support for ECDSARecover according to the same signature as is described in KRYPTO.ml.

**Comment by dwightguth** [comment]
I ran into two distinct bugs in the Java backend that caused kompile to fail with an exception while trying to test my pull request that adds ECDSARecover support to UIUCK. I will upload that pull request now, but it's not tested and I can't guarantee it will actually work. Someone else needs to debug the errors in UIUCK because I am not going to wade into that festering cesspool.

**Comment by dwightguth** [comment]
@ehildenb I believe this should be ready for review and should hopefully pass the tests. We're not running the blockchain tests with uiuck yet, and there's still a little bit of work needed to match the output files, but this should be sufficient for the existing tests to run. If I could get a review and if you're satisfied, merge this, that would be good.

**Pull request closed without merging**
