### PR TITLE
fix invalid #lookup.* rule names in concrete-rules.txt

### PR DESCRIPTION
**Pull request by daejunpark**
Fix a bug introduced at https://github.com/kframework/evm-semantics/commit/223f21ce46625298962413953e388f5eccfefd58#diff-558a5f8e4337c04713ebea82c99dde22R19-R20

### CODE REVIEW

**Comment by daejunpark** [comment]
@denis-bogdanas @ehildenb I made this as a separate PR, to see if this doesn't break the existing proofs.

**Comment by ehildenb** [comment]
@daejunpark I'm pretty sure the file `tests/specs/concrete-rules.txt` isn't used by _any_ of the proofs. Can you just remove it?

The `Makefile` currently does this:

```
tests/%.prove: tests/%
    $(TEST) prove $(TEST_OPTIONS) --backend $(TEST_SYMBOLIC_BACKEND) $< $(KPROVE_MODULE) --format-failures $(KPROVE_OPTS) \
        --concrete-rules $(shell cat $(dir $@)concrete-rules.txt | tr '\n' ',')
```

which only looks for `concrete-rules.txt` next to the current proof, not at this global file.

**Comment by ehildenb** [comment]
Ah, I just saw that this file is symlinked from many proofs, which is why it's there.

@daejunpark since this doesn't seem to break the proofs, can you just _remove_ those lines from `concrete-rules.txt` instead? I would like that file to be as small as possible, and it seems we discovered a place where we can make it smaller.

**Comment by denis-bogdanas** [comment]
Those 2 lines must be removed. They don't help with #852

**Comment by daejunpark** [comment]
@denis-bogdanas Ah, I misunderstood that you mentioned it could help.  OK I just removed them.

@ehildenb I agree with you.

**Pull request merged**
