### PR TITLE
.build/k: update k submodule

### PR DESCRIPTION
**Pull request by daejunpark**

### CODE REVIEW

**Comment by daejunpark** [comment]
@dwightguth Any idea about the jenkins build error?

```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.io.ObjectStreamClass
        ...
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.kframework.utils.BinaryLoader.load(BinaryLoader.java:92)
	at org.kframework.utils.BinaryLoader.load(BinaryLoader.java:99)
	at org.kframework.utils.BinaryLoader.load(BinaryLoader.java:74)
	at org.kframework.kompile.DefinitionParsing.parseModules(DefinitionParsing.java:112)
	at org.kframework.kompile.Kompile.parseModules(Kompile.java:273)
	at org.kframework.kprove.KProve.getProofDefinition(KProve.java:96)
	at org.kframework.kprove.KProve.run(KProve.java:55)
	at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:96)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:107)
	at org.kframework.main.Main.main(Main.java:53)
```

**Comment by dwightguth** [comment]
No, I have no idea why that might happen, but I'd suggest running the tests again, which it looks like you have.

**Comment by daejunpark** [comment]
@dwightguth thanks. now it passes.

**Comment by daejunpark** [comment]
@ehildenb it is ready to review

**Pull request merged**
