### PR TITLE
chop: %Int => modInt

### PR DESCRIPTION
**Pull request by daejunpark**
Do not merge. Just to see what happens.

### CODE REVIEW

**Comment by pirapira** [comment]
Oh, sorry, I rebased a branch that's not mine.

**Comment by dwightguth** [comment]
Do we want to merge this?

**Comment by daejunpark** [comment]
@dwightguth Not sure. Clearly, `%Int` is wrong when `I` is negative, although @ehildenb believes that no negative values can appear during the execution. Still this change makes sense and better to be merged just in case. But the thing is that there are many other places where such a questionable `%Int` is still used instead of `modInt`, and I'm not sure how much merging this single change will make the definition robust.

**Comment by daejunpark** [comment]
close this and open #115

**Pull request closed without merging**
