### PR TITLE
Rebase/sol proofs

### PR DESCRIPTION
**Pull request by msaxena2**
WIP. Not ready for merge yet.

### CODE REVIEW

**Comment by msaxena2** [comment]
@daejunpark This is ready for an review. Once this is merged, #116 will be updated with these commits (this branch is already rebased on verification). We can then make final changes to #116 and open it for review.

**Comment by daejunpark** [comment]
@msaxena2 vyper => viper

**Comment by msaxena2** [comment]
@daejunpark https://github.com/ethereum/vyper/pull/630 - Don't have any reservations about the name. Just chose whatever was the name of the repo. I tested the proofs locally, but they'll all be run (both solidity and v[yi]per by jenkins as well.

**Comment by msaxena2** [comment]
@nishantjr Seems to be some problems with the test harness. The concrete tests did pass though. Will investigate tomorrow.

**Comment by daejunpark** [comment]
@msaxena2 I see. I didn't know that they changed the name. Thanks for bringing it up.

**Comment by daejunpark** [comment]
re-opened  #119

**Pull request merged**
