### PR TITLE
readme quickfix

### PR DESCRIPTION
**Pull request by MrChico**

### CODE REVIEW

**Comment by dwightguth** [comment]
Jenkins: test this please

**Comment by dwightguth** [comment]
Jenkins: test mantis

**Comment by ehildenb** [comment]
Thanks for the fix, can you look at `git log` and see the style of commit messages we're using? `git commit --amend` will let you change your commit message.

**Comment by MrChico** [comment]
@ehildenb Updated the commit message

**Comment by ehildenb** [comment]
Subsumed by #204 .

**Pull request closed without merging**
